# Application Configuration
baseurl =  https://the-internet.herokuapp.com
abtesturl = https://the-internet.herokuapp.com/abtest
addDeleteurl = https://the-internet.herokuapp.com/add_remove_elements/
basicAuthUrl = https://admin:admin@the-internet.herokuapp.com/basic_auth
brokenImagesUrl = https://the-internet.herokuapp.com/broken_images
challengingDomUrl = https://the-internet.herokuapp.com/challenging_dom
checkboxurl = https://the-internet.herokuapp.com/checkboxes
contextMenuUrl = https://the-internet.herokuapp.com/context_menu
digestAuthUrl = https://the-internet.herokuapp.com/digest_auth
disappearingElementsUrl = https://the-internet.herokuapp.com/disappearing_elements
dragDropUrl = https://the-internet.herokuapp.com/drag_and_drop
dropDownUrl = https://the-internet.herokuapp.com/dropdown
dynamicContentUrl = https://the-internet.herokuapp.com/dynamic_content
dynamicControlsUrl = https://the-internet.herokuapp.com/dynamic_controls
dynamicElementUrl = https://the-internet.herokuapp.com/dynamic_loading/
entryAdUrl = https://the-internet.herokuapp.com/entry_ad
downloadFileUrl = https://the-internet.herokuapp.com/download
uploadFileUrl = https://the-internet.herokuapp.com/upload
floatingMenuUrl = https://the-internet.herokuapp.com/floating_menu
forgotPasswordUrl = https://the-internet.herokuapp.com/forgot_password
nestedFramesUrl = https://the-internet.herokuapp.com/nested_frames
iFrameUrl = https://the-internet.herokuapp.com/iframe
geoLocationUrl = https://the-internet.herokuapp.com/geolocation
horizontalSliderUrl = https://the-internet.herokuapp.com/horizontal_slider
hoversUrl = https://the-internet.herokuapp.com/hovers
infiniteScrollUrl = https://the-internet.herokuapp.com/infinite_scroll
inputsUrl = https://the-internet.herokuapp.com/inputs
jqueryuiUrl = https://the-internet.herokuapp.com/jqueryui/menu
jsAlertsUrl = https://the-internet.herokuapp.com/javascript_alerts
jsErrorUrl = https://the-internet.herokuapp.com/javascript_error
keyPressesUrl = https://the-internet.herokuapp.com/key_presses
largeDeepDomUrl = https://the-internet.herokuapp.com/large
newWindowUrl = https://the-internet.herokuapp.com/windows
notificationUrl = https://the-internet.herokuapp.com/notification_message_rendered
redirectionUrl = https://the-internet.herokuapp.com/redirector
secureDownloadUrl = https://admin:admin@the-internet.herokuapp.com/download_secure
shadowDomUrl = https://the-internet.herokuapp.com/shadowdom
shiftingContentMenuUrl = https://the-internet.herokuapp.com/shifting_content/menu
statusCodesUrl = https://the-internet.herokuapp.com/status_codes

loginurl = https://the-internet.herokuapp.com/login
dropdownurl = https://the-internet.herokuapp.com/dropdown

# Browser Configuration
browser = CHROME
headless=true

# Timeout Configuration
implicitWait = 5
explicitWait = 10

# Retry counts Configuration
maxRetryCount = 2

# Path configuration
screenshotPath = target/screenshots/
jsonDataPath = testdata/loginData.json
excelDataPath = testdata/ChallengingDomData.xlsx

# Data Configuration
tableHeaderCount = 7
tableDataRowCount = 10

#Custom Configurations
locLat = 31
locLong = 74
promptText = Playwright Java